version: '3.8'
# definir container
services:


  db:
    image: mysql:latest
    restart: unless-stopped
    ports:
      - "3309:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: tpachato
    volumes:
      - db_data:/var/lib/mysql
  # spring app
  backend:
    image: adem8100/achat:v1.0
    restart: unless-stopped
    ports:
      - "8089:8089"
    depends_on:
      - db

volumes:
  db_data: